server:
  port: 8202

spring:
  application:
    name: dkl-server-test

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.url}:8848

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:8301/auth/user

feign:
  hystrix:
    enabled: true

hystrix:
  shareSecurityContext: true
