server:
  port: 8301

spring:
  application:
    name: dkl-gateway
  #关闭数据装配
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.url}:8848


zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: dkl-auth
      sensitiveHeaders: "*"
    system:
      path: /system/**
      serviceId: dkl-server-system
      sensitiveHeaders: "*"
    test:
      path: /test/**
      serviceId: dkl-server-test
      sensitiveHeaders: "*"
  retryable: true
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
  SendErrorFilter:
    error:
      disable: true

ribbon:
  ReadTimeout: 3000
